### ISSUE TITLE
Can not build code on source code 

### ISSUE THREAD

**Issue by oneheed** [Eniwder/artactree#1]
![image](https://user-images.githubusercontent.com/18730285/112151591-5e0fd180-8c1c-11eb-876d-7762198e5547.png)

---
Whether the file is missing

/assets/res/type_magic.png
/assets/res/type_sword.png
...

can help me

**Comment by Eniwder** [comment]
These images are excluded purposely because they are got informal methods.
So it's in the specifications for avoiding abuse.

However, this tool is published as Web App so you can find them easily at docs dir.
It's a hassle, but please find, rename and place.

**Comment by Eniwder** [comment]
This is an additional information.
Getting some images were troublesome because they are encoded to base64, so I attach only them here.

[icons.zip](https://github.com/Eniwder/artactree/files/6190121/icons.zip)

**Comment by oneheed** [comment]
sorry assets/sass/style.scss  is missing

**Comment by Eniwder** [comment]
This is my mistake!
I pushed them.
